apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: hf-planner-dev
type: Opaque
stringData:
  # Note: USER and DB are not sensitive, but kept here for convenience
  POSTGRES_USER: hfplanner
  POSTGRES_PASSWORD: hfplanner
  POSTGRES_DB: hfplanner
  # Connection string for backend to use
  DATABASE_URL: postgresql://hfplanner:hfplanner@postgres-service:5432/hfplanner
