from datetime import time

from sqlalchemy import func
from sqlmodel import Session, create_engine, select

from app.core.config import settings
from app.models import Concert

engine = create_engine(settings.DATABASE_URL)

concerts_data = [
    # ===================== THURSDAY 18 JUNE =====================
    # MAINSTAGE 1
    {
        "band_name": "We Came As Romans",
        "day": "Thursday",
        "festival_day": "Thursday",
        "start_time": time(16, 0),
        "end_time": time(16, 40),
        "stage": "Mainstage 1",
    },
    {
        "band_name": "The Plot In You",
        "day": "Thursday",
        "festival_day": "Thursday",
        "start_time": time(17, 30),
        "end_time": time(18, 10),
        "stage": "Mainstage 1",
    },
    {
        "band_name": "Breaking Benjamin",
        "day": "Thursday",
        "festival_day": "Thursday",
        "start_time": time(19, 5),
        "end_time": time(19, 55),
        "stage": "Mainstage 1",
    },
    {
        "band_name": "Papa Roach",
        "day": "Thursday",
        "festival_day": "Thursday",
        "start_time": time(21, 20),
        "end_time": time(22, 25),
        "stage": "Mainstage 1",
    },
    {
        "band_name": "Bring Me The Horizon",
        "day": "Thursday",
        "festival_day": "Thursday",
        "start_time": time(23, 35),
        "end_time": time(0, 50),
        "stage": "Mainstage 1",
    },
    # MAINSTAGE 2
    {
        "band_name": "Mikkey Dee With Friends",
        "day": "Thursday",
        "festival_day": "Thursday",
        "start_time": time(16, 45),
        "end_time": time(17, 25),
        "stage": "Mainstage 2",
    },
    {
        "band_name": "The Pretty Reckless",
        "day": "Thursday",
        "festival_day": "Thursday",
        "start_time": time(18, 15),
        "end_time": time(19, 0),
        "stage": "Mainstage 2",
    },
    {
        "band_name": "Deep Purple",
        "day": "Thursday",
        "festival_day": "Thursday",
        "start_time": time(20, 0),
        "end_time": time(21, 15),
        "stage": "Mainstage 2",
    },
    {
        "band_name": "Alice Cooper",
        "day": "Thursday",
        "festival_day": "Thursday",
        "start_time": time(22, 30),
        "end_time": time(23, 30),
        "stage": "Mainstage 2",
    },
    {
        "band_name": "Alestorm",
        "day": "Friday",
        "festival_day": "Thursday",
        "start_time": time(0, 55),
        "end_time": time(1, 45),
        "stage": "Mainstage 2",
    },
    # WARZONE
    {
        "band_name": "Satanic Surfers",
        "day": "Thursday",
        "festival_day": "Thursday",
        "start_time": time(16, 45),
        "end_time": time(17, 25),
        "stage": "Warzone",
    },
    {
        "band_name": "Shelter",
        "day": "Thursday",
        "festival_day": "Thursday",
        "start_time": time(18, 15),
        "end_time": time(19, 0),
        "stage": "Warzone",
    },
    {
        "band_name": "Lagwagon",
        "day": "Thursday",
        "festival_day": "Thursday",
        "start_time": time(20, 0),
        "end_time": time(21, 0),
        "stage": "Warzone",
    },
    {
        "band_name": "All Time Low",
        "day": "Thursday",
        "festival_day": "Thursday",
        "start_time": time(22, 10),
        "end_time": time(23, 10),
        "stage": "Warzone",
    },
    {
        "band_name": "Social Distortion",
        "day": "Friday",
        "festival_day": "Thursday",
        "start_time": time(0, 30),
        "end_time": time(1, 30),
        "stage": "Warzone",
    },
    # VALLEY
    {
        "band_name": "Truckfighters",
        "day": "Thursday",
        "festival_day": "Thursday",
        "start_time": time(16, 0),
        "end_time": time(16, 40),
        "stage": "Valley",
    },
    {
        "band_name": "Elder",
        "day": "Thursday",
        "festival_day": "Thursday",
        "start_time": time(17, 30),
        "end_time": time(18, 10),
        "stage": "Valley",
    },
    {
        "band_name": "The Inspector Cluzo",
        "day": "Thursday",
        "festival_day": "Thursday",
        "start_time": time(19, 5),
        "end_time": time(19, 55),
        "stage": "Valley",
    },
    {
        "band_name": "Uncle Acid And The Deadbeats",
        "day": "Thursday",
        "festival_day": "Thursday",
        "start_time": time(21, 5),
        "end_time": time(22, 5),
        "stage": "Valley",
    },
    {
        "band_name": "Kadavar",
        "day": "Thursday",
        "festival_day": "Thursday",
        "start_time": time(23, 15),
        "end_time": time(0, 25),
        "stage": "Valley",
    },
    # TEMPLE
    {
        "band_name": "Perchta",
        "day": "Thursday",
        "festival_day": "Thursday",
        "start_time": time(16, 45),
        "end_time": time(17, 25),
        "stage": "Temple",
    },
    {
        "band_name": "Winterfylleth",
        "day": "Thursday",
        "festival_day": "Thursday",
        "start_time": time(18, 15),
        "end_time": time(19, 0),
        "stage": "Temple",
    },
    {
        "band_name": "Borknagar",
        "day": "Thursday",
        "festival_day": "Thursday",
        "start_time": time(20, 0),
        "end_time": time(21, 0),
        "stage": "Temple",
    },
    {
        "band_name": "Skåld",
        "day": "Thursday",
        "festival_day": "Thursday",
        "start_time": time(22, 10),
        "end_time": time(23, 10),
        "stage": "Temple",
    },
    {
        "band_name": "Feuerschwanz",
        "day": "Friday",
        "festival_day": "Thursday",
        "start_time": time(0, 30),
        "end_time": time(1, 30),
        "stage": "Temple",
    },
    # ALTAR
    {
        "band_name": "Skaphos",
        "day": "Thursday",
        "festival_day": "Thursday",
        "start_time": time(16, 0),
        "end_time": time(16, 40),
        "stage": "Altar",
    },
    {
        "band_name": "Devangelic",
        "day": "Thursday",
        "festival_day": "Thursday",
        "start_time": time(17, 30),
        "end_time": time(18, 10),
        "stage": "Altar",
    },
    {
        "band_name": "Rivers of Nihil",
        "day": "Thursday",
        "festival_day": "Thursday",
        "start_time": time(19, 5),
        "end_time": time(19, 55),
        "stage": "Altar",
    },
    {
        "band_name": "The Halo Effect",
        "day": "Thursday",
        "festival_day": "Thursday",
        "start_time": time(21, 5),
        "end_time": time(22, 5),
        "stage": "Altar",
    },
    {
        "band_name": "Igorrr",
        "day": "Thursday",
        "festival_day": "Thursday",
        "start_time": time(23, 15),
        "end_time": time(0, 25),
        "stage": "Altar",
    },
    # ===================== FRIDAY 19 JUNE =====================
    # MAINSTAGE 1
    {
        "band_name": "Blackrain",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(11, 5),
        "end_time": time(11, 35),
        "stage": "Mainstage 1",
    },
    {
        "band_name": "Wings of Steel",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(12, 15),
        "end_time": time(12, 45),
        "stage": "Mainstage 1",
    },
    {
        "band_name": "Sortilège",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(13, 35),
        "end_time": time(14, 15),
        "stage": "Mainstage 1",
    },
    {
        "band_name": "Queensrÿche",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(15, 5),
        "end_time": time(15, 50),
        "stage": "Mainstage 1",
    },
    {
        "band_name": "Accept",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(16, 45),
        "end_time": time(17, 35),
        "stage": "Mainstage 1",
    },
    {
        "band_name": "Helloween",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(18, 35),
        "end_time": time(19, 55),
        "stage": "Mainstage 1",
    },
    {
        "band_name": "Iron Maiden",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(21, 0),
        "end_time": time(23, 10),
        "stage": "Mainstage 1",
    },
    {
        "band_name": "Ultra Vomit",
        "day": "Saturday",
        "festival_day": "Friday",
        "start_time": time(0, 50),
        "end_time": time(2, 0),
        "stage": "Mainstage 1",
    },
    # MAINSTAGE 2
    {
        "band_name": "Uravena",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(10, 30),
        "end_time": time(11, 0),
        "stage": "Mainstage 2",
    },
    {
        "band_name": "Return to Dust",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(11, 40),
        "end_time": time(12, 10),
        "stage": "Mainstage 2",
    },
    {
        "band_name": "Brothers of Metal",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(12, 50),
        "end_time": time(13, 30),
        "stage": "Mainstage 2",
    },
    {
        "band_name": "Tesseract",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(14, 20),
        "end_time": time(15, 0),
        "stage": "Mainstage 2",
    },
    {
        "band_name": "Bloodywood",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(15, 55),
        "end_time": time(16, 40),
        "stage": "Mainstage 2",
    },
    {
        "band_name": "Sepultura",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(17, 40),
        "end_time": time(18, 30),
        "stage": "Mainstage 2",
    },
    {
        "band_name": "Opeth",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(20, 0),
        "end_time": time(20, 55),
        "stage": "Mainstage 2",
    },
    {
        "band_name": "Sabaton",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(23, 15),
        "end_time": time(0, 45),
        "stage": "Mainstage 2",
    },
    # WARZONE
    {
        "band_name": "Wake the Dead",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(11, 5),
        "end_time": time(11, 35),
        "stage": "Warzone",
    },
    {
        "band_name": "Gridiron",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(12, 15),
        "end_time": time(12, 45),
        "stage": "Warzone",
    },
    {
        "band_name": "Die Spitz",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(13, 35),
        "end_time": time(14, 15),
        "stage": "Warzone",
    },
    {
        "band_name": "Point Mort",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(15, 5),
        "end_time": time(15, 50),
        "stage": "Warzone",
    },
    {
        "band_name": "Dying Wish",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(16, 45),
        "end_time": time(17, 35),
        "stage": "Warzone",
    },
    {
        "band_name": "Ceremony",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(18, 35),
        "end_time": time(19, 25),
        "stage": "Warzone",
    },
    {
        "band_name": "Malevolence",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(20, 35),
        "end_time": time(21, 35),
        "stage": "Warzone",
    },
    {
        "band_name": "La Dispute",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(22, 45),
        "end_time": time(23, 45),
        "stage": "Warzone",
    },
    {
        "band_name": "The Dillinger Escape Plan",
        "day": "Saturday",
        "festival_day": "Friday",
        "start_time": time(0, 55),
        "end_time": time(2, 0),
        "stage": "Warzone",
    },
    # VALLEY
    {
        "band_name": "Draguinov",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(10, 30),
        "end_time": time(11, 0),
        "stage": "Valley",
    },
    {
        "band_name": "Yarostan",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(11, 40),
        "end_time": time(12, 10),
        "stage": "Valley",
    },
    {
        "band_name": "Rezn",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(12, 50),
        "end_time": time(13, 30),
        "stage": "Valley",
    },
    {
        "band_name": "Conjurer",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(14, 20),
        "end_time": time(15, 0),
        "stage": "Valley",
    },
    {
        "band_name": "Stoned Jesus",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(15, 55),
        "end_time": time(16, 40),
        "stage": "Valley",
    },
    {
        "band_name": "Torche",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(17, 40),
        "end_time": time(18, 30),
        "stage": "Valley",
    },
    {
        "band_name": "Loathe",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(19, 30),
        "end_time": time(20, 30),
        "stage": "Valley",
    },
    {
        "band_name": "Slift",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(21, 40),
        "end_time": time(22, 40),
        "stage": "Valley",
    },
    {
        "band_name": "Mastodon",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(23, 50),
        "end_time": time(0, 50),
        "stage": "Valley",
    },
    # ALTAR
    {
        "band_name": "Impureza",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(10, 30),
        "end_time": time(11, 0),
        "stage": "Altar",
    },
    {
        "band_name": "Esodic",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(11, 40),
        "end_time": time(12, 10),
        "stage": "Altar",
    },
    {
        "band_name": "Crypta",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(12, 50),
        "end_time": time(13, 30),
        "stage": "Altar",
    },
    {
        "band_name": "Blood Red Throne",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(14, 20),
        "end_time": time(15, 0),
        "stage": "Altar",
    },
    {
        "band_name": "Sinsaenum",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(15, 55),
        "end_time": time(16, 40),
        "stage": "Altar",
    },
    {
        "band_name": "Sylosis",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(17, 40),
        "end_time": time(18, 30),
        "stage": "Altar",
    },
    {
        "band_name": "Decapitated",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(19, 30),
        "end_time": time(20, 30),
        "stage": "Altar",
    },
    {
        "band_name": "Periphery",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(21, 40),
        "end_time": time(22, 40),
        "stage": "Altar",
    },
    {
        "band_name": "Blood Incantation",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(23, 50),
        "end_time": time(0, 50),
        "stage": "Altar",
    },
    # TEMPLE
    {
        "band_name": "Mourir",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(11, 5),
        "end_time": time(11, 35),
        "stage": "Temple",
    },
    {
        "band_name": "Killus",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(12, 15),
        "end_time": time(12, 45),
        "stage": "Temple",
    },
    {
        "band_name": "Ponte Del Diavolo",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(13, 35),
        "end_time": time(14, 15),
        "stage": "Temple",
    },
    {
        "band_name": "Einherjer",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(15, 5),
        "end_time": time(15, 50),
        "stage": "Temple",
    },
    {
        "band_name": "Trelldom",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(16, 45),
        "end_time": time(17, 35),
        "stage": "Temple",
    },
    {
        "band_name": "Carach Angren",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(18, 35),
        "end_time": time(19, 25),
        "stage": "Temple",
    },
    {
        "band_name": "Rotting Christ",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(20, 35),
        "end_time": time(21, 35),
        "stage": "Temple",
    },
    {
        "band_name": "My Dying Bride",
        "day": "Friday",
        "festival_day": "Friday",
        "start_time": time(22, 45),
        "end_time": time(23, 45),
        "stage": "Temple",
    },
    {
        "band_name": "The Gathering",
        "day": "Saturday",
        "festival_day": "Friday",
        "start_time": time(0, 55),
        "end_time": time(2, 0),
        "stage": "Temple",
    },
    # ===================== SATURDAY 20 JUNE =====================
    # MAINSTAGE 1
    {
        "band_name": "Slay Squad",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(11, 5),
        "end_time": time(11, 35),
        "stage": "Mainstage 1",
    },
    {
        "band_name": "Thornhill",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(12, 25),
        "end_time": time(13, 5),
        "stage": "Mainstage 1",
    },
    {
        "band_name": "House of Protection",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(13, 55),
        "end_time": time(14, 35),
        "stage": "Mainstage 1",
    },
    {
        "band_name": "Enhancer",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(15, 25),
        "end_time": time(16, 5),
        "stage": "Mainstage 1",
    },
    {
        "band_name": "Static-X",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(16, 55),
        "end_time": time(17, 40),
        "stage": "Mainstage 1",
    },
    {
        "band_name": "Tom Morello",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(18, 35),
        "end_time": time(19, 25),
        "stage": "Mainstage 1",
    },
    {
        "band_name": "A Perfect Circle",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(20, 35),
        "end_time": time(21, 45),
        "stage": "Mainstage 1",
    },
    {
        "band_name": "Limp Bizkit",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(23, 10),
        "end_time": time(0, 40),
        "stage": "Mainstage 1",
    },
    # MAINSTAGE 2
    {
        "band_name": "Locomuerte",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(10, 30),
        "end_time": time(11, 0),
        "stage": "Mainstage 2",
    },
    {
        "band_name": "Insanity Alert",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(11, 40),
        "end_time": time(12, 20),
        "stage": "Mainstage 2",
    },
    {
        "band_name": "Escuela Grind",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(13, 10),
        "end_time": time(13, 50),
        "stage": "Mainstage 2",
    },
    {
        "band_name": "Gatecreeper",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(14, 40),
        "end_time": time(15, 20),
        "stage": "Mainstage 2",
    },
    {
        "band_name": "Crisix",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(16, 10),
        "end_time": time(16, 50),
        "stage": "Mainstage 2",
    },
    {
        "band_name": 'Cavalera "Chaos A.D."',
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(17, 45),
        "end_time": time(18, 30),
        "stage": "Mainstage 2",
    },
    {
        "band_name": "Anthrax",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(19, 30),
        "end_time": time(20, 30),
        "stage": "Mainstage 2",
    },
    {
        "band_name": "Megadeth",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(21, 50),
        "end_time": time(23, 5),
        "stage": "Mainstage 2",
    },
    {
        "band_name": "Volbeat",
        "day": "Sunday",
        "festival_day": "Saturday",
        "start_time": time(0, 45),
        "end_time": time(2, 0),
        "stage": "Mainstage 2",
    },
    # WARZONE
    {
        "band_name": "False Reality",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(11, 5),
        "end_time": time(11, 35),
        "stage": "Warzone",
    },
    {
        "band_name": "Combust",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(12, 25),
        "end_time": time(13, 5),
        "stage": "Warzone",
    },
    {
        "band_name": "King 810",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(13, 55),
        "end_time": time(14, 35),
        "stage": "Warzone",
    },
    {
        "band_name": "Cancer Bats",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(15, 25),
        "end_time": time(16, 5),
        "stage": "Warzone",
    },
    {
        "band_name": "Trash Talk",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(16, 55),
        "end_time": time(17, 40),
        "stage": "Warzone",
    },
    {
        "band_name": "Cro-Mags",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(18, 35),
        "end_time": time(19, 25),
        "stage": "Warzone",
    },
    {
        "band_name": "Kublai Khan TX",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(20, 35),
        "end_time": time(21, 35),
        "stage": "Warzone",
    },
    {
        "band_name": "Lionheart",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(22, 45),
        "end_time": time(23, 45),
        "stage": "Warzone",
    },
    {
        "band_name": "Hatebreed",
        "day": "Sunday",
        "festival_day": "Saturday",
        "start_time": time(0, 55),
        "end_time": time(2, 0),
        "stage": "Warzone",
    },
    # VALLEY
    {
        "band_name": "Cold.Capsule",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(10, 30),
        "end_time": time(11, 0),
        "stage": "Valley",
    },
    {
        "band_name": "Bruit ≤",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(11, 40),
        "end_time": time(12, 20),
        "stage": "Valley",
    },
    {
        "band_name": "Fange",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(13, 10),
        "end_time": time(13, 50),
        "stage": "Valley",
    },
    {
        "band_name": "Psychonaut",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(14, 40),
        "end_time": time(15, 20),
        "stage": "Valley",
    },
    {
        "band_name": "Pigs Pigs Pigs Pigs Pigs Pigs Pigs",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(16, 10),
        "end_time": time(16, 50),
        "stage": "Valley",
    },
    {
        "band_name": "God Is An Astronaut",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(17, 45),
        "end_time": time(18, 30),
        "stage": "Valley",
    },
    {
        "band_name": "The Young Gods",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(19, 30),
        "end_time": time(20, 30),
        "stage": "Valley",
    },
    {
        "band_name": "Amenra",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(21, 40),
        "end_time": time(22, 40),
        "stage": "Valley",
    },
    {
        "band_name": "Cult of Luna",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(23, 50),
        "end_time": time(0, 50),
        "stage": "Valley",
    },
    # ALTAR
    {
        "band_name": "DVRK",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(10, 30),
        "end_time": time(11, 0),
        "stage": "Altar",
    },
    {
        "band_name": "Profanation",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(11, 40),
        "end_time": time(12, 20),
        "stage": "Altar",
    },
    {
        "band_name": "Cabal",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(13, 10),
        "end_time": time(13, 50),
        "stage": "Altar",
    },
    {
        "band_name": "Defeated Sanity",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(14, 40),
        "end_time": time(15, 20),
        "stage": "Altar",
    },
    {
        "band_name": "Severe Torture",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(16, 10),
        "end_time": time(16, 50),
        "stage": "Altar",
    },
    {
        "band_name": "Obscura",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(17, 45),
        "end_time": time(18, 30),
        "stage": "Altar",
    },
    {
        "band_name": "Septicflesh",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(19, 30),
        "end_time": time(20, 30),
        "stage": "Altar",
    },
    {
        "band_name": "Carcass",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(21, 40),
        "end_time": time(22, 40),
        "stage": "Altar",
    },
    {
        "band_name": "Deicide",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(23, 50),
        "end_time": time(0, 50),
        "stage": "Altar",
    },
    # TEMPLE
    {
        "band_name": "Vigljós",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(11, 5),
        "end_time": time(11, 35),
        "stage": "Temple",
    },
    {
        "band_name": "Hulder",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(12, 25),
        "end_time": time(13, 5),
        "stage": "Temple",
    },
    {
        "band_name": "Non Est Deus",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(13, 55),
        "end_time": time(14, 35),
        "stage": "Temple",
    },
    {
        "band_name": "1914",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(15, 25),
        "end_time": time(16, 5),
        "stage": "Temple",
    },
    {
        "band_name": "Gaerea",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(16, 55),
        "end_time": time(17, 40),
        "stage": "Temple",
    },
    {
        "band_name": "Oranssi Pazuzu",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(18, 35),
        "end_time": time(19, 25),
        "stage": "Temple",
    },
    {
        "band_name": "Aura Noir",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(20, 35),
        "end_time": time(21, 35),
        "stage": "Temple",
    },
    {
        "band_name": "Old Man's Child",
        "day": "Saturday",
        "festival_day": "Saturday",
        "start_time": time(22, 45),
        "end_time": time(23, 45),
        "stage": "Temple",
    },
    {
        "band_name": "Behemoth",
        "day": "Sunday",
        "festival_day": "Saturday",
        "start_time": time(0, 55),
        "end_time": time(2, 0),
        "stage": "Temple",
    },
    # ===================== SUNDAY 21 JUNE =====================
    # MAINSTAGE 1
    {
        "band_name": "Not Scientists",
        "day": "Sunday",
        "festival_day": "Sunday",
        "start_time": time(11, 5),
        "end_time": time(11, 35),
        "stage": "Mainstage 1",
    },
    {
        "band_name": "The Dwarves",
        "day": "Sunday",
        "festival_day": "Sunday",
        "start_time": time(12, 15),
        "end_time": time(12, 45),
        "stage": "Mainstage 1",
    },
    {
        "band_name": "The Bones",
        "day": "Sunday",
        "festival_day": "Sunday",
        "start_time": time(13, 35),
        "end_time": time(14, 15),
        "stage": "Mainstage 1",
    },
    {
        "band_name": "The Ataris",
        "day": "Sunday",
        "festival_day": "Sunday",
        "start_time": time(15, 10),
        "end_time": time(15, 55),
        "stage": "Mainstage 1",
    },
    {
        "band_name": "Pennywise",
        "day": "Sunday",
        "festival_day": "Sunday",
        "start_time": time(16, 50),
        "end_time": time(17, 40),
        "stage": "Mainstage 1",
    },
    {
        "band_name": "Rise Against",
        "day": "Sunday",
        "festival_day": "Sunday",
        "start_time": time(18, 40),
        "end_time": time(19, 40),
        "stage": "Mainstage 1",
    },
    {
        "band_name": "The Hives",
        "day": "Sunday",
        "festival_day": "Sunday",
        "start_time": time(20, 50),
        "end_time": time(21, 50),
        "stage": "Mainstage 1",
    },
    {
        "band_name": "The Offspring",
        "day": "Sunday",
        "festival_day": "Sunday",
        "start_time": time(23, 15),
        "end_time": time(0, 30),
        "stage": "Mainstage 1",
    },
    # MAINSTAGE 2
    {
        "band_name": "The Funeral Portrait",
        "day": "Sunday",
        "festival_day": "Sunday",
        "start_time": time(10, 30),
        "end_time": time(11, 0),
        "stage": "Mainstage 2",
    },
    {
        "band_name": "Revnoir",
        "day": "Sunday",
        "festival_day": "Sunday",
        "start_time": time(11, 40),
        "end_time": time(12, 10),
        "stage": "Mainstage 2",
    },
    {
        "band_name": "Resolve",
        "day": "Sunday",
        "festival_day": "Sunday",
        "start_time": time(12, 50),
        "end_time": time(13, 30),
        "stage": "Mainstage 2",
    },
    {
        "band_name": "President",
        "day": "Sunday",
        "festival_day": "Sunday",
        "start_time": time(14, 20),
        "end_time": time(15, 5),
        "stage": "Mainstage 2",
    },
    {
        "band_name": "Black Veil Brides",
        "day": "Sunday",
        "festival_day": "Sunday",
        "start_time": time(16, 0),
        "end_time": time(16, 45),
        "stage": "Mainstage 2",
    },
    {
        "band_name": "Three Days Grace",
        "day": "Sunday",
        "festival_day": "Sunday",
        "start_time": time(17, 45),
        "end_time": time(18, 35),
        "stage": "Mainstage 2",
    },
    {
        "band_name": "Architects",
        "day": "Sunday",
        "festival_day": "Sunday",
        "start_time": time(19, 45),
        "end_time": time(20, 45),
        "stage": "Mainstage 2",
    },
    {
        "band_name": "Bad Omens",
        "day": "Sunday",
        "festival_day": "Sunday",
        "start_time": time(21, 55),
        "end_time": time(23, 10),
        "stage": "Mainstage 2",
    },
    # WARZONE
    {
        "band_name": "Karen Dio",
        "day": "Sunday",
        "festival_day": "Sunday",
        "start_time": time(10, 30),
        "end_time": time(11, 0),
        "stage": "Warzone",
    },
    {
        "band_name": "Maid of Ace",
        "day": "Sunday",
        "festival_day": "Sunday",
        "start_time": time(11, 40),
        "end_time": time(12, 10),
        "stage": "Warzone",
    },
    {
        "band_name": "End It",
        "day": "Sunday",
        "festival_day": "Sunday",
        "start_time": time(12, 50),
        "end_time": time(13, 30),
        "stage": "Warzone",
    },
    {
        "band_name": "Drain",
        "day": "Sunday",
        "festival_day": "Sunday",
        "start_time": time(14, 20),
        "end_time": time(15, 5),
        "stage": "Warzone",
    },
    {
        "band_name": "Buzzcocks",
        "day": "Sunday",
        "festival_day": "Sunday",
        "start_time": time(16, 0),
        "end_time": time(16, 45),
        "stage": "Warzone",
    },
    {
        "band_name": "Circle Jerks",
        "day": "Sunday",
        "festival_day": "Sunday",
        "start_time": time(17, 45),
        "end_time": time(18, 35),
        "stage": "Warzone",
    },
    {
        "band_name": "Agnostic Front",
        "day": "Sunday",
        "festival_day": "Sunday",
        "start_time": time(19, 45),
        "end_time": time(20, 45),
        "stage": "Warzone",
    },
    {
        "band_name": "The Adicts",
        "day": "Sunday",
        "festival_day": "Sunday",
        "start_time": time(21, 55),
        "end_time": time(23, 10),
        "stage": "Warzone",
    },
    # VALLEY
    {
        "band_name": "Alta Rossa",
        "day": "Sunday",
        "festival_day": "Sunday",
        "start_time": time(11, 5),
        "end_time": time(11, 35),
        "stage": "Valley",
    },
    {
        "band_name": "Gnome",
        "day": "Sunday",
        "festival_day": "Sunday",
        "start_time": time(12, 15),
        "end_time": time(12, 45),
        "stage": "Valley",
    },
    {
        "band_name": "Black Tusk",
        "day": "Sunday",
        "festival_day": "Sunday",
        "start_time": time(13, 35),
        "end_time": time(14, 15),
        "stage": "Valley",
    },
    {
        "band_name": "Soilent Green",
        "day": "Sunday",
        "festival_day": "Sunday",
        "start_time": time(15, 10),
        "end_time": time(15, 55),
        "stage": "Valley",
    },
    {
        "band_name": "Eyehategod",
        "day": "Sunday",
        "festival_day": "Sunday",
        "start_time": time(16, 50),
        "end_time": time(17, 40),
        "stage": "Valley",
    },
    {
        "band_name": "Corrosion of Conformity",
        "day": "Sunday",
        "festival_day": "Sunday",
        "start_time": time(18, 40),
        "end_time": time(19, 40),
        "stage": "Valley",
    },
    {
        "band_name": "Acid Bath",
        "day": "Sunday",
        "festival_day": "Sunday",
        "start_time": time(20, 50),
        "end_time": time(21, 50),
        "stage": "Valley",
    },
    {
        "band_name": "Down",
        "day": "Sunday",
        "festival_day": "Sunday",
        "start_time": time(23, 15),
        "end_time": time(0, 30),
        "stage": "Valley",
    },
    # ALTAR
    {
        "band_name": "Tempt Fate",
        "day": "Sunday",
        "festival_day": "Sunday",
        "start_time": time(10, 30),
        "end_time": time(11, 0),
        "stage": "Altar",
    },
    {
        "band_name": "Bloodstain",
        "day": "Sunday",
        "festival_day": "Sunday",
        "start_time": time(11, 40),
        "end_time": time(12, 10),
        "stage": "Altar",
    },
    {
        "band_name": "Sublime Cadaveric Decomposition",
        "day": "Sunday",
        "festival_day": "Sunday",
        "start_time": time(12, 50),
        "end_time": time(13, 30),
        "stage": "Altar",
    },
    {
        "band_name": "Fulci",
        "day": "Sunday",
        "festival_day": "Sunday",
        "start_time": time(14, 20),
        "end_time": time(15, 5),
        "stage": "Altar",
    },
    {
        "band_name": "Six Feet Under",
        "day": "Sunday",
        "festival_day": "Sunday",
        "start_time": time(16, 0),
        "end_time": time(16, 45),
        "stage": "Altar",
    },
    {
        "band_name": "Forbidden",
        "day": "Sunday",
        "festival_day": "Sunday",
        "start_time": time(17, 45),
        "end_time": time(18, 35),
        "stage": "Altar",
    },
    {
        "band_name": "Possessed",
        "day": "Sunday",
        "festival_day": "Sunday",
        "start_time": time(19, 45),
        "end_time": time(20, 45),
        "stage": "Altar",
    },
    {
        "band_name": "Napalm Death",
        "day": "Sunday",
        "festival_day": "Sunday",
        "start_time": time(21, 55),
        "end_time": time(23, 10),
        "stage": "Altar",
    },
    # TEMPLE
    {
        "band_name": "Silhouette",
        "day": "Sunday",
        "festival_day": "Sunday",
        "start_time": time(11, 5),
        "end_time": time(11, 35),
        "stage": "Temple",
    },
    {
        "band_name": "Midnight Odyssey",
        "day": "Sunday",
        "festival_day": "Sunday",
        "start_time": time(12, 15),
        "end_time": time(12, 45),
        "stage": "Temple",
    },
    {
        "band_name": "Thy Light",
        "day": "Sunday",
        "festival_day": "Sunday",
        "start_time": time(13, 35),
        "end_time": time(14, 15),
        "stage": "Temple",
    },
    {
        "band_name": "Scour",
        "day": "Sunday",
        "festival_day": "Sunday",
        "start_time": time(15, 10),
        "end_time": time(15, 55),
        "stage": "Temple",
    },
    {
        "band_name": "Gehenna",
        "day": "Sunday",
        "festival_day": "Sunday",
        "start_time": time(16, 50),
        "end_time": time(17, 40),
        "stage": "Temple",
    },
    {
        "band_name": "Wolves In The Throne Room",
        "day": "Sunday",
        "festival_day": "Sunday",
        "start_time": time(18, 40),
        "end_time": time(19, 40),
        "stage": "Temple",
    },
    {
        "band_name": "Marduk",
        "day": "Sunday",
        "festival_day": "Sunday",
        "start_time": time(20, 50),
        "end_time": time(21, 50),
        "stage": "Temple",
    },
    {
        "band_name": "Mayhem",
        "day": "Sunday",
        "festival_day": "Sunday",
        "start_time": time(23, 15),
        "end_time": time(0, 30),
        "stage": "Temple",
    },
]

# Maps (festival_day, stage, new_band_name) -> old_band_name in DB
# Used by update_concert_times to handle name corrections
_name_corrections: dict[tuple[str, str, str], str] = {
    ("Thursday", "Temple", "Skåld"): "Skáld",
    ("Friday", "Valley", "Draguinov"): "Dragunov",
    ("Friday", "Temple", "Einherjer"): "Einherjær",
    ("Saturday", "Altar", "DVRK"): "DVRX",
    ("Saturday", "Temple", "Vigljós"): "Viglios",
}


def seed_concerts():
    with Session(engine) as session:
        # Count existing concerts efficiently using database-level count
        statement = select(func.count()).select_from(Concert)
        existing_concerts = session.exec(statement).one()

        if existing_concerts > 0:
            print(f"Database already contains {existing_concerts} concerts. Skipping seed.")
            return

        for concert_data in concerts_data:
            concert = Concert(**concert_data)
            session.add(concert)

        session.commit()
        print(f"Successfully seeded {len(concerts_data)} concerts!")


def update_concert_times():
    """Update start_time, end_time, day and fix band name typos for all concerts.

    Matches existing DB records by (band_name, festival_day, stage).
    Falls back to _name_corrections for known name mismatches between seed and DB.
    Favorites are preserved since concert IDs are not changed.
    """
    with Session(engine) as session:
        updated = 0
        not_found = []

        for data in concerts_data:
            band = data["band_name"]
            festival_day = data["festival_day"]
            stage = data["stage"]

            stmt = select(Concert).where(
                Concert.band_name == band,
                Concert.festival_day == festival_day,
                Concert.stage == stage,
            )
            concert = session.exec(stmt).first()

            if concert is None:
                old_name = _name_corrections.get((festival_day, stage, band))
                if old_name:
                    stmt = select(Concert).where(
                        Concert.band_name == old_name,
                        Concert.festival_day == festival_day,
                        Concert.stage == stage,
                    )
                    concert = session.exec(stmt).first()

            if concert is None:
                not_found.append(f"{band} ({festival_day}, {stage})")
                continue

            concert.band_name = band
            concert.start_time = data["start_time"]
            concert.end_time = data["end_time"]
            concert.day = data["day"]
            session.add(concert)
            updated += 1

        session.commit()
        print(f"Updated {updated} concerts.")
        if not_found:
            print(f"Not found ({len(not_found)}): {', '.join(not_found)}")


if __name__ == "__main__":
    seed_concerts()
