"""initial_schema

Revision ID: 3790bfd154bc
Revises:
Create Date: 2026-01-07 17:18:06.368127

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "3790bfd154bc"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "concerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("band_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("day", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("festival_day", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("stage", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_concerts_band_name"), "concerts", ["band_name"], unique=False)
    op.create_index(op.f("ix_concerts_day"), "concerts", ["day"], unique=False)
    op.create_index(op.f("ix_concerts_festival_day"), "concerts", ["festival_day"], unique=False)
    op.create_index(op.f("ix_concerts_stage"), "concerts", ["stage"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("favorites_public", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_favorites_public"), "users", ["favorites_public"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "favorites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("concert_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["concert_id"],
            ["concerts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "concert_id", name="unique_user_concert"),
    )
    op.create_index(op.f("ix_favorites_concert_id"), "favorites", ["concert_id"], unique=False)
    op.create_index(op.f("ix_favorites_user_id"), "favorites", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_favorites_user_id"), table_name="favorites")
    op.drop_index(op.f("ix_favorites_concert_id"), table_name="favorites")
    op.drop_table("favorites")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_favorites_public"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_concerts_stage"), table_name="concerts")
    op.drop_index(op.f("ix_concerts_festival_day"), table_name="concerts")
    op.drop_index(op.f("ix_concerts_day"), table_name="concerts")
    op.drop_index(op.f("ix_concerts_band_name"), table_name="concerts")
    op.drop_table("concerts")
    # ### end Alembic commands ###
